---
- name: Install nginx if os is ubuntu
  apt: 
    name: nginx
    update_cache: yes
    state: present
  when: ansible_os_family == "Debian"

- name: Install nginx if os is Redhat
  yum: 
    name: nginx
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"